config/routes.rb
Rails.application.routes.draw do

  resources :users do
    resources :posts
  end
  resources :comments

  get "/" => "users#login"
  get "/login" => "users#login"
  get "/signin" => "users#signin"
  get "/home" => "users#home"
  get "/signout" => "users#signout"
  post "/user/:id/posts" => "posts#create"
  get "/posts_index" => "posts#index"
  get "/new_adress" => "address#new"

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
  validates :street, :city, :state, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  validates :username, presence: true
  validates :username, length: {minimum: 4, maximum: 30}
  validates :email, confirmation: true
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(address_params)

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.fetch(:address, {})
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # ======= GET / =======
  def index
    puts "\n******* post/index *******"
    puts "** session[:user_id], #{session[:user_id]}"
    @user = User.where(id: session[:user_id]).first
    @posts = Post.where(user_id: session[:user_id])
  end

  # ======= GET /show/:id =======
  def show
    puts "\n******* show *******"
    puts "\n** params.inspect: #{params.inspect}"
    @user = User.where(id: session[:user_id]).first
    # @comments = @user.comments
    @post = Post.find(@post)
    @comments = Comment.where(post_id: @post.id)
    puts "** @post.inspect: #{@post.inspect}"
    puts "** @comments.inspect: #{@comments.inspect}"

  end

  # ======= GET /post/new =======
  def new
    puts "\n******* new *******"
    puts "** params.inspect: #{params.inspect}"
    @user = User.where(id: session[:user_id]).first
    @post = @user.posts.build
    puts "@user.inspect, #{@user.inspect}"
    puts "@post.inspect, #{@post.inspect}"
end

  # ======= GET /posts/:id/edit =======
  def edit
    puts "\n******* edit *******"
  end

  # ======= POST /posts =======
  def create
    puts "\n******* create *******"
    puts "\n** post_params.inspect: #{post_params.inspect}"
    @user = User.where(id: session[:user_id]).first
    @post = @user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to "/posts_index", notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # ======= PATCH/PUT /posts/:id =======
  def update
    puts "\n******* update *******"
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # ======= DELETE /posts/:id =======
  def destroy
    puts "\n******* destroy *******"
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_posts_path, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :require_login

  # ======= GET /user =======
  def signin
    puts "\n******* signin *******"
    puts "\n** signin_params.inspect: #{signin_params.inspect} *******"
    @user = User.where(username: signin_params[:username]).first
    puts "\n******* USER OK *******"
    if @user && User.where(password: signin_params[:password])
       puts "\n******* PSWD OK *******"
       puts "** @user.inspect: #{@user.inspect}"
       puts "** @user[:id].inspect: #{@user[:id].inspect}"
       session[:user_id] = @user.id
       puts "** session[:user_id]: #{session[:user_id]}"
       redirect_to "/home", :flash => { :success => "Welcome!" }
     else
       redirect_to "/"
     end
   end

  def signout
    puts "\n******* signout *******"
    session[:user_id] = nil
    redirect_to "/login"
  end

  # ======= GET /login =======
  def login
    puts "\n******* login *******"
    @user = User.new
    @users = User.all
  end

  # ======= GET / =======
  def index
    puts "\n******* index *******"
    @users = User.all
  end

  def home
    puts "\n******* home *******"
    @postsArray = []
    @users = User.all
    @users.each do |user|
      posts = user.posts
      if posts.length > 0
        @postsArray << posts
      else
        @postsArray << "no_post"
      end
    end
  end

  # ======= GET /show/:id =======
  def show
    puts "\n******* show *******"
  end

  # ======= GET /user/new =======
  def new
    puts "\n******* new *******"
    @user = User.new
  end

  # ======= GET /users/:id/edit =======
  def edit
    puts "\n******* edit *******"
  end

  # ======= POST /users =======
  def create
    puts "\n******* create *******"
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # ======= PATCH/PUT /users/:id =======
  def update
    puts "\n******* update *******"
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # ======= DELETE /users/:id =======
  def destroy
    puts "\n******* destroy *******"
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  private
    # def require_login
		# 	unless logged_in?
		# 	flash[:error] = "You must be logged in to access this section"
		# 	redirect_to "login"
    #   end
    # end

    def signin_params
      puts "\n******* signin_params"
      params.permit(:username, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:fname, :lname, :email, :username, :password)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for(address) do |f| %>
  <% if address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_for(address) do |f| %>
    <div class="actions">
        <p><%= f.text_field :street %><%= f.label :street %></p>
        <p><%= f.text_field :city %><%= f.label :city %></p>
        <p><%= f.text_field :state %><%= f.label :state %></p>
        <p><%= f.text_field :zip %><%= f.label :zip %></p>
        <%= f.submit %>
    </div>
    <% end %>

  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form', address: @address %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addresses</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New Address</h1>

<%= render 'form', address: @address %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/comments/_form.html.erb
<%= form_for([@post.user, @post]) do |f| %>
  <% puts "@user.inspect, #{@user.inspect}" %>
  <% puts "@post.inspect, #{@post.inspect}" %>

      <p><%= f.text_field :title %><%= f.label(:title, "title") %></p>
    <p><%= f.text_area :content, size: "80x10" %><%= f.label(:content, "content") %></p>
    <%= f.submit "Save" %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', post: @post %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final Rails Blog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!-- ======= ======= ======= body ======= ======= ======= -->
  <body>

      <!-- == header == -->
      <div id="header" class="section">
          <p>header</p>
          <%= render :partial => "/users/menu"%>
      </div>

      <!-- == yield == -->
      <div id="yield" class="section">
          <%= yield %>
      </div>

      <!-- == footer == -->
      <div id="footer" class="section">
          <p>footer</p>
      </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@post.user, @post]) do |f| %>
  <% puts "@user.inspect, #{@user.inspect}" %>
  <% puts "@post.inspect, #{@post.inspect}" %>

  <p><%= f.text_field :title %><%= f.label(:title, "title") %></p>
  <p><%= f.text_area :content, size: "80x10" %><%= f.label(:content, "content") %></p>
  <%= f.submit "Save" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.fname + " " + @user.lname %>'s Posts</h1>

<table>
  <thead>
    <tr>
      <th id="title">title</th>
      <th id="content">content</th>
      <th id="edit">edit</th>
      <th id="delete">delete</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, user_post_path(user_id: session[:user_id], id: post.id) %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Edit', edit_user_post_path(user_id: session[:user_id], id: post.id) %></td>
        <td><%= link_to 'Destroy', user_post_path(user_id: session[:user_id], id: post.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.fname + " " + @user.lname %>'s Posts</h1>

<div class="postTitle"> <%= @post.title %> </div>
<div class="postContent"> <%= @post.content %> </div>
<div class="postComments">
  <% @comments.each do |comment| %>
    <br><%= comment.content %>
    <br>-<%= comment.user.fname %>
  <% end %>
</div>


<%= link_to 'Edit', edit_user_post_path(session[:user_id], @post) %> |
<%= link_to 'Back', user_posts_path(session[:user_id]) %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_for(user) do |f| %>
    <div class="actions">
        <p><%= f.text_field :fname %><%= f.label :fname %></p>
        <p><%= f.text_field :lname %><%= f.label :lname %></p>
        <p><%= f.text_field :email %><%= f.label :email %></p>
        <p><%= f.text_field :email_confirmation%><%= f.label :confirm %></p>
        <p><%= f.text_field :username %><%= f.label :username %></p>
        <p><%= f.text_field :password %><%= f.label :password %></p>
        <%= f.submit %>
    </div>
    <% end %>

  </div>
<% end %>

app/views/users/_menu.html.erb
<h1>menu</h1>
<div class="menu" id="menuItems">

  <% puts "** menu session[:user_id]: #{session[:user_id]}" %>
  <% if session[:user_id] %>
    <%= link_to 'All Users', "/home" %>
    <%= link_to 'My Posts', user_posts_path(user_id: session[:user_id]) %>
    <%= link_to 'New Post', new_user_post_path(user_id: session[:user_id]) %>

    <%= link_to 'Log Out', "/signout" %>
  <% else %>
    <%= link_to 'New User', new_user_path %>
    <%= link_to 'Log in', "/login" %>
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<h1>Home</h1>

<% @users.each_with_index do |user, index| %>
 <% user_post = @postsArray[index].first %>
 <% puts "** user_post.inspect: #{user_post.inspect}" %>
 <div class="user-box">
  <div class="name-link">
    <%= link_to user.fname + " " + user.lname, user_posts_path(user) %>
  </div>
  <div class="post-title">
    <% if user_post != "n" %>
      <%= user_post.title %>
    <% else %>
    <p class="empty-text">no posts for this user</p>
    <% end %>
  </div>
  <div class="post_content">
    <% if user_post != "n" %>
      <%= user_post.content %>
    <% end %>
  </div>
 </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table id="user-table">
  <thead>
    <tr>
      <th id="user">user</th>
      <th id="edit">edit</th>
      <th id="delete">delete</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.fname + " " + user.lname, user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/login.html.erb
<h1>Login</h1>

<%= form_tag("/signin", method: "get") do %>
    <p><%= text_field_tag :username, value = "xl003" %><%= label_tag(:username, "username") %></p>
    <p><%= text_field_tag :password, value = "luo123" %><%= label_tag(:password, "password") %></p>
    <%= submit_tag "Login" %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', "/login" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>